// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxvdwmqpqflxnhjhknld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54dmR3bXFwcWZseG5oamhrbmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMjcwOTMsImV4cCI6MjA2MTkwMzA5M30.gS0-M0QXvOVZU6Dy6KJDbukc-u2Atr6eUGYlcSUsgos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);